POST http://localhost:8000/users
Content-Type: application/json

{
    "username": "foo",
    "email": "foo@email.com",
    "first_name": "Foo",
    "last_name": "Bar",
    "password": "bar"
}

###

POST http://localhost:8000/users
Content-Type: application/json

{
    "username": "bar",
    "email": "bar@email.com",
    "first_name": "Bar",
    "last_name": "Foo",
    "password": "foo"
}
